
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lblnumero1;
	private global::Gtk.Label lblnumero2;
	private global::Gtk.Label lblnumero3;
	private global::Gtk.Entry entry1;
	private global::Gtk.Entry entry2;
	private global::Gtk.Entry entry3;
	private global::Gtk.Button btnsumar;
	private global::Gtk.Button btnrestar;
	private global::Gtk.Button btnmultiplicar;
	private global::Gtk.Button btndividir;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnumero1 = new global::Gtk.Label ();
		this.lblnumero1.Name = "lblnumero1";
		this.lblnumero1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lblnumero1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnumero1]));
		w1.X = 50;
		w1.Y = 55;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnumero2 = new global::Gtk.Label ();
		this.lblnumero2.Name = "lblnumero2";
		this.lblnumero2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.lblnumero2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnumero2]));
		w2.X = 52;
		w2.Y = 142;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblnumero3 = new global::Gtk.Label ();
		this.lblnumero3.Name = "lblnumero3";
		this.lblnumero3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lblnumero3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lblnumero3]));
		w3.X = 52;
		w3.Y = 221;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w4.X = 188;
		w4.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
		w5.X = 188;
		w5.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.fixed1.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
		w6.X = 189;
		w6.Y = 211;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnsumar = new global::Gtk.Button ();
		this.btnsumar.CanFocus = true;
		this.btnsumar.Name = "btnsumar";
		this.btnsumar.UseUnderline = true;
		this.btnsumar.Label = global::Mono.Unix.Catalog.GetString ("Sumar");
		this.fixed1.Add (this.btnsumar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnsumar]));
		w7.X = 424;
		w7.Y = 47;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnrestar = new global::Gtk.Button ();
		this.btnrestar.CanFocus = true;
		this.btnrestar.Name = "btnrestar";
		this.btnrestar.UseUnderline = true;
		this.btnrestar.Label = global::Mono.Unix.Catalog.GetString ("Restar");
		this.fixed1.Add (this.btnrestar);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnrestar]));
		w8.X = 426;
		w8.Y = 101;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnmultiplicar = new global::Gtk.Button ();
		this.btnmultiplicar.CanFocus = true;
		this.btnmultiplicar.Name = "btnmultiplicar";
		this.btnmultiplicar.UseUnderline = true;
		this.btnmultiplicar.Label = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		this.fixed1.Add (this.btnmultiplicar);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnmultiplicar]));
		w9.X = 418;
		w9.Y = 151;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btndividir = new global::Gtk.Button ();
		this.btndividir.CanFocus = true;
		this.btndividir.Name = "btndividir";
		this.btndividir.UseUnderline = true;
		this.btndividir.Label = global::Mono.Unix.Catalog.GetString ("Dividir");
		this.fixed1.Add (this.btndividir);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btndividir]));
		w10.X = 425;
		w10.Y = 210;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 529;
		this.DefaultHeight = 302;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnsumar.Clicked += new global::System.EventHandler (this.OnBtnsumarClicked);
		this.btnrestar.Clicked += new global::System.EventHandler (this.OnBtnrestarClicked);
		this.btnmultiplicar.Clicked += new global::System.EventHandler (this.OnBtnmultiplicarClicked);
		this.btndividir.Clicked += new global::System.EventHandler (this.OnBtndividirClicked);
	}
}
